# Generated by Django 3.2.13 on 2022-05-02 10:31

import django.core.validators
from django.db import migrations, models
import events.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(max_length=10, unique=True, validators=[events.validators.validate_iran_national_code], verbose_name='کدملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='لطفا شماره موبایل معتبری وارد نمایید!', regex='^(0)?9\\d{9}$')], verbose_name='شماره موبایل'),
        ),
    ]
