# Generated by Django 3.2.10 on 2022-04-24 03:55

import django.core.validators
from django.db import migrations, models
import events.validators


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='remaining_capacity',
            field=models.PositiveIntegerField(verbose_name='ظرفیت باقیمانده'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='full_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='لطفا از کیبورد فارسی استفاده کنید.', regex='^[\u0600-ۿ\\s]+$')], verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='national_code',
            field=models.CharField(max_length=10, unique=True, validators=[events.validators.validate_iran_national_code], verbose_name='کدملی'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(default=1, max_length=14, validators=[django.core.validators.RegexValidator(message='Please Enter a Valid Phone Number!', regex='^(0)?9\\d{9}$')], verbose_name='شماره موبایل'),
            preserve_default=False,
        ),
    ]
