# Generated by Django 3.2.13 on 2022-05-02 11:27

from django.db import migrations, models
import events.validators


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20220502_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='national_code',
            field=models.CharField(max_length=10, validators=[events.validators.validate_iran_national_code], verbose_name='کدملی'),
        ),
    ]
