# Generated by Django 3.2.13 on 2022-05-09 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('events', '0004_alter_ticket_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_team_set', to='team.team', verbose_name='تیم مهمان'),
        ),
        migrations.AlterField(
            model_name='event',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_team_set', to='team.team', verbose_name='تیم میزبان'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
