# Generated by Django 3.2.13 on 2022-05-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='home_banner',
            field=models.ImageField(blank=True, help_text='لطفا تصویری با عرض ۱۹۲۰ و ارتفاع ۸۱۰ پیکسل بارگذاری نمایید.', null=True, upload_to='site_settings', verbose_name='بنر صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='home_link',
            field=models.URLField(blank=True, default='belitmes.ir', null=True, verbose_name='لینک صفحه اصلی'),
        ),
    ]
